# Generated by Django 4.2.2 on 2023-06-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.CharField(blank=True, default=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(choices=[(' Rated G', 'Rated G'), ('Rated PG ', 'Rated Pg'), ('Rated PG 13', 'Rated Pg 13'), ('Rated R', 'Rated R'), ('Rated NC 17', 'Rated Nc 17')], default=' Rated G', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default=None, max_length=127),
            preserve_default=False,
        ),
    ]
