# Generated by Django 4.2.2 on 2023-06-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_duration_movie_rating_movie_synopsis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(blank=True, choices=[(' Rated G', 'Rated G'), ('Rated PG ', 'Rated Pg'), ('Rated PG 13', 'Rated Pg 13'), ('Rated R', 'Rated R'), ('Rated NC 17', 'Rated Nc 17')], default=' Rated G', max_length=20, null=True),
        ),
    ]
