# Generated by Django 4.2.2 on 2023-06-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(blank=True, choices=[('G', 'Rated G'), ('PG ', 'Rated Pg'), ('PG 13', 'Rated Pg 13'), ('R', 'Rated R'), ('NC 17', 'Rated Nc 17')], default='G', max_length=20, null=True),
        ),
    ]
