# Generated by Django 4.2.2 on 2023-06-15 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_rename_added_by_movie_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='user',
            new_name='users',
        ),
    ]
