# Generated by Django 4.2.2 on 2023-06-15 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_rename_user_movie_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='users',
            new_name='user',
        ),
    ]
